name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build CarService API
        run: |
          chmod +x ./CarService/gradlew
          cd CarService && ./gradlew :CarServiceApi:clean :CarServiceApi:publishToMavenLocal


      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests

      # - name: Build images
      #   timeout-minutes: 10
      #   run: docker compose build

      # - name: Run containers
      #   timeout-minutes: 5
      #   run: |
      #     docker compose up -d
      #     ./scripts/wait-script.sh
      #   env:
      #     WAIT_PORTS: 8080,8070,8060,8050

      # - name: Run API Tests
      #   uses: matt-ball/newman-action@master
      #   with:
      #     # TODO insert your variant
      #     collection: <variant>/postman/collection.json
      #     environment: <variant>/postman/environment.json
      #     delayRequest: 100
      #     reporters: '[ "cli" ]'

      # - uses: education/autograding@v1
      #   id: autograder
      #   continue-on-error: true

      # - name: Github auto grader mark
      #   uses: Romanow/google-sheet-autograder-marker@v1.0
      #   with:
      #     google_token: ${{secrets.GOOGLE_API_KEY}}
      #     sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
      #     homework_number: 2
      #     user_column: 'D'
      #     column_offset: 'F'
      #     mark: "'+"

      # - name: Stop containers
      #   if: always()
      #   continue-on-error: true
      #   run: docker compose down -v
